# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_des1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#####################
import pickle
from persiantools.jdatetime import JalaliDate, JalaliDateTime

#####################


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(466, 810)
        Form.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                           "color:gold;")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.notifLable = QtWidgets.QLabel(Form)
        self.notifLable.setText("")
        self.notifLable.setObjectName("notifLable")
        self.gridLayout.addWidget(
            self.notifLable, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.main_tabWidget = QtWidgets.QTabWidget(Form)
        self.main_tabWidget.setMinimumSize(QtCore.QSize(442, 721))
        self.main_tabWidget.setMaximumSize(QtCore.QSize(442, 721))
        self.main_tabWidget.setStyleSheet("*{border: 1px solid rgba(164,170,182,0.1);\n"
                                          "selection-background-color: rgb(143, 255, 112);\n"
                                          "selection-color: rgb(42, 255, 232);\n"
                                          "background-color: rgb(49, 51, 59);\n"
                                          "border-radius: 8px;\n"
                                          "}\n"
                                          "\n"
                                          "#main_tabWidget :pressed {\n"
                                          "    background-color: gold;\n"
                                          "    color:  rgb(41, 43, 53);\n"
                                          "}    ")
        self.main_tabWidget.setObjectName("main_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page)
        self.groupBox_9.setMinimumSize(QtCore.QSize(261, 316))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_day = QtWidgets.QComboBox(self.groupBox_2)
        self.search_day.setMinimumSize(QtCore.QSize(121, 31))
        self.search_day.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_day.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.search_day.setStyleSheet("*{\n"
                                      "background: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;\n"
                                      "}\n"
                                      "\n"
                                      "#create_dey:pressed {\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.search_day.setObjectName("search_day")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.search_day.addItem("")
        self.horizontalLayout_2.addWidget(self.search_day)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setStyleSheet("border: none;")
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.search_month = QtWidgets.QComboBox(self.groupBox_2)
        self.search_month.setMinimumSize(QtCore.QSize(121, 31))
        self.search_month.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_month.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.search_month.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                        "border-radius:5px;\n"
                                        "color: gold;\n"
                                        "}\n"
                                        "#create_month:pressed{\n"
                                        "    background-color: gold;\n"
                                        "    color:  black;\n"
                                        "}    ")
        self.search_month.setObjectName("search_month")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.search_month.addItem("")
        self.horizontalLayout_2.addWidget(self.search_month)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setStyleSheet("border: none;")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.line1_5 = QtWidgets.QFrame(self.groupBox_9)
        self.line1_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_5.setObjectName("line1_5")
        self.verticalLayout_10.addWidget(self.line1_5)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_11.setStyleSheet("border: 1px solid rgba(164,170,182,0.1);\n"
                                       "background-color: rgb(49, 51, 59);\n"
                                       "border-radius: 8px;")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.search_origin = QtWidgets.QLineEdit(self.groupBox_11)
        self.search_origin.setMinimumSize(QtCore.QSize(215, 31))
        self.search_origin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.search_origin.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                         "border-radius:5px;\n"
                                         "color: gold;}\n"
                                         "\n"
                                         "#search_origin:fouces{\n"
                                         "    background: gold;\n"
                                         "    color:  rgb(41, 43, 53);\n"
                                         "}    ")
        self.search_origin.setObjectName("search_origin")
        self.verticalLayout_5.addWidget(self.search_origin)
        self.search_dest = QtWidgets.QLineEdit(self.groupBox_11)
        self.search_dest.setMinimumSize(QtCore.QSize(215, 31))
        self.search_dest.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.search_dest.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                       "border-radius:5px;\n"
                                       "color: gold;")
        self.search_dest.setObjectName("search_dest")
        self.verticalLayout_5.addWidget(self.search_dest)
        self.verticalLayout_10.addWidget(self.groupBox_11)
        self.line1_4 = QtWidgets.QFrame(self.groupBox_9)
        self.line1_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_4.setObjectName("line1_4")
        self.verticalLayout_10.addWidget(self.line1_4)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_12.setStyleSheet("border: 1px solid rgba(164,170,182,0.1);\n"
                                       "background-color: rgb(49, 51, 59);\n"
                                       "border-radius: 8px;")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.search_travel_b = QtWidgets.QPushButton(self.groupBox_12)
        self.search_travel_b.setMinimumSize(QtCore.QSize(215, 31))
        self.search_travel_b.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_travel_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                           "border-radius:5px;\n"
                                           "color: gold;}\n"
                                           "\n"
                                           "#search_travel_b:pressed {\n"
                                           "    background: gold;\n"
                                           "    color:  rgb(41, 43, 53);\n"
                                           "}    ")
        self.search_travel_b.setObjectName("search_travel_b")
        self.verticalLayout_9.addWidget(self.search_travel_b)
        self.verticalLayout_10.addWidget(self.groupBox_12)
        self.myticket_b = QtWidgets.QPushButton(self.groupBox_9)
        self.myticket_b.setMinimumSize(QtCore.QSize(215, 31))
        self.myticket_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.myticket_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;}\n"
                                      "\n"
                                      "#myticket_b:pressed {\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.myticket_b.setObjectName("myticket_b")
        self.verticalLayout_10.addWidget(self.myticket_b)
        self.verticalLayout_18.addWidget(self.groupBox_9)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setMinimumSize(QtCore.QSize(351, 18))
        self.label_10.setMaximumSize(QtCore.QSize(351, 18))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_23.addWidget(self.label_10)
        self.listWidget_2 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_2.setMinimumSize(QtCore.QSize(350, 0))
        self.listWidget_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.listWidget_2.setStyleSheet("*{\n"
                                        "background: rgb(41, 43, 53);\n"
                                        "border-radius:5px;\n"
                                        "color: gold;\n"
                                        "}\n"
                                        "\n"
                                        "#listWidget_2:pressed {\n"
                                        "    background: gold;\n"
                                        "    color:  rgb(41, 43, 53);\n"
                                        "}    ")
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_23.addWidget(self.listWidget_2)
        self.return_b1 = QtWidgets.QPushButton(self.page_2)
        self.return_b1.setMinimumSize(QtCore.QSize(350, 30))
        self.return_b1.setMaximumSize(QtCore.QSize(350, 30))
        self.return_b1.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                     "border-radius:5px;\n"
                                     "color: gold;}\n"
                                     "\n"
                                     "#return_b1:pressed {\n"
                                     "    background: gold;\n"
                                     "    color:  rgb(41, 43, 53);\n"
                                     "}    ")
        self.return_b1.setObjectName("return_b1")
        self.verticalLayout_23.addWidget(self.return_b1)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.name_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.name_input.setMinimumSize(QtCore.QSize(215, 31))
        self.name_input.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.name_input.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;}\n"
                                      "\n"
                                      "#search_origin:fouces{\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.name_input.setObjectName("name_input")
        self.verticalLayout_24.addWidget(self.name_input)
        self.meliCode_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.meliCode_input.setMinimumSize(QtCore.QSize(215, 31))
        self.meliCode_input.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                          "border-radius:5px;\n"
                                          "color: gold;}\n"
                                          "\n"
                                          "#search_origin:fouces{\n"
                                          "    background: gold;\n"
                                          "    color:  rgb(41, 43, 53);\n"
                                          "}    ")
        self.meliCode_input.setObjectName("meliCode_input")
        self.verticalLayout_24.addWidget(self.meliCode_input)
        self.number_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.number_input.setMinimumSize(QtCore.QSize(215, 31))
        self.number_input.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                        "border-radius:5px;\n"
                                        "color: gold;}\n"
                                        "\n"
                                        "#search_origin:fouces{\n"
                                        "    background: gold;\n"
                                        "    color:  rgb(41, 43, 53);\n"
                                        "}    ")
        self.number_input.setObjectName("number_input")
        self.verticalLayout_24.addWidget(self.number_input)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_2.setMinimumSize(QtCore.QSize(215, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.passangerNumber_input = QtWidgets.QSpinBox(self.frame_2)
        self.passangerNumber_input.setMinimumSize(QtCore.QSize(80, 31))
        self.passangerNumber_input.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                                 "border-radius:5px;\n"
                                                 "color: gold;")
        self.passangerNumber_input.setObjectName("passangerNumber_input")
        self.horizontalLayout_4.addWidget(self.passangerNumber_input)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("border: 0px,")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_24.addWidget(self.frame_2)
        self.confrim_input_b = QtWidgets.QPushButton(self.groupBox_3)
        self.confrim_input_b.setMinimumSize(QtCore.QSize(340, 30))
        self.confrim_input_b.setMaximumSize(QtCore.QSize(340, 30))
        self.confrim_input_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                           "border-radius:5px;\n"
                                           "color: gold;}\n"
                                           "\n"
                                           "#confrim_input_b:pressed {\n"
                                           "    background: gold;\n"
                                           "    color:  rgb(41, 43, 53);\n"
                                           "}    ")
        self.confrim_input_b.setObjectName("confrim_input_b")
        self.verticalLayout_24.addWidget(self.confrim_input_b)
        self.return_b2 = QtWidgets.QPushButton(self.groupBox_3)
        self.return_b2.setMinimumSize(QtCore.QSize(340, 30))
        self.return_b2.setMaximumSize(QtCore.QSize(340, 30))
        self.return_b2.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                     "border-radius:5px;\n"
                                     "color: gold;}\n"
                                     "\n"
                                     "#return_b2:pressed {\n"
                                     "    background: gold;\n"
                                     "    color:  rgb(41, 43, 53);\n"
                                     "}    ")
        self.return_b2.setObjectName("return_b2")
        self.verticalLayout_24.addWidget(self.return_b2)
        self.verticalLayout_25.addWidget(self.groupBox_3)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_3 = QtWidgets.QFrame(self.page_7)
        self.frame_3.setStyleSheet("border:0px,\n"
                                   "")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_27.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.page_7)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.code_input = QtWidgets.QLineEdit(self.frame_5)
        self.code_input.setMinimumSize(QtCore.QSize(215, 31))
        self.code_input.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;}\n"
                                      "\n"
                                      "#search_origin:fouces{\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.code_input.setObjectName("code_input")
        self.verticalLayout_3.addWidget(self.code_input)
        self.find_b = QtWidgets.QPushButton(self.frame_5)
        self.find_b.setMinimumSize(QtCore.QSize(340, 30))
        self.find_b.setMaximumSize(QtCore.QSize(340, 30))
        self.find_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                  "border-radius:5px;\n"
                                  "color: gold;}\n"
                                  "\n"
                                  "#find_b:pressed {\n"
                                  "    background: gold;\n"
                                  "    color:  rgb(41, 43, 53);\n"
                                  "}    ")
        self.find_b.setObjectName("find_b")
        self.verticalLayout_3.addWidget(self.find_b)
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(340, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(340, 30))
        self.pushButton_7.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                        "border-radius:5px;\n"
                                        "color: gold;}\n"
                                        "\n"
                                        "#pushButton_7:pressed {\n"
                                        "    background: gold;\n"
                                        "    color:  rgb(41, 43, 53);\n"
                                        "}    ")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.verticalLayout_27.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.page_7)
        self.frame_4.setStyleSheet("border:0px,\n"
                                   "")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_27.addWidget(self.frame_4)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setMinimumSize(QtCore.QSize(351, 18))
        self.label_11.setMaximumSize(QtCore.QSize(351, 18))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_26.addWidget(self.label_11)
        self.listWidget_3 = QtWidgets.QListWidget(self.page_6)
        self.listWidget_3.setMinimumSize(QtCore.QSize(350, 0))
        self.listWidget_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.listWidget_3.setStyleSheet("*{\n"
                                        "background: rgb(41, 43, 53);\n"
                                        "border-radius:5px;\n"
                                        "color: gold;\n"
                                        "}\n"
                                        "\n"
                                        "#listWidget_2:pressed {\n"
                                        "    background: gold;\n"
                                        "    color:  rgb(41, 43, 53);\n"
                                        "}    ")
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_26.addWidget(self.listWidget_3)
        self.return_b4 = QtWidgets.QPushButton(self.page_6)
        self.return_b4.setMinimumSize(QtCore.QSize(350, 30))
        self.return_b4.setMaximumSize(QtCore.QSize(350, 30))
        self.return_b4.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                     "border-radius:5px;\n"
                                     "color: gold;}\n"
                                     "\n"
                                     "#return_b4:pressed {\n"
                                     "    background: gold;\n"
                                     "    color:  rgb(41, 43, 53);\n"
                                     "}    ")
        self.return_b4.setObjectName("return_b4")
        self.verticalLayout_26.addWidget(self.return_b4)
        self.stackedWidget_2.addWidget(self.page_6)
        self.verticalLayout_22.addWidget(self.stackedWidget_2)
        self.main_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.log_form = QtWidgets.QWidget()
        self.log_form.setObjectName("log_form")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.log_form)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.log_tabWidget = QtWidgets.QTabWidget(self.log_form)
        self.log_tabWidget.setObjectName("log_tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_17.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.singup_username = QtWidgets.QLineEdit(self.groupBox_17)
        self.singup_username.setMinimumSize(QtCore.QSize(215, 31))
        self.singup_username.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.singup_username.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                           "border-radius:5px;\n"
                                           "color: gold;")
        self.singup_username.setObjectName("singup_username")
        self.verticalLayout_17.addWidget(self.singup_username)
        self.username_input_3 = QtWidgets.QLineEdit(self.groupBox_17)
        self.username_input_3.setMinimumSize(QtCore.QSize(215, 31))
        self.username_input_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.username_input_3.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                            "border-radius:5px;\n"
                                            "color: gold;")
        self.username_input_3.setObjectName("username_input_3")
        self.verticalLayout_17.addWidget(self.username_input_3)
        self.pass_username = QtWidgets.QLineEdit(self.groupBox_17)
        self.pass_username.setMinimumSize(QtCore.QSize(215, 31))
        self.pass_username.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pass_username.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                         "border-radius:5px;\n"
                                         "color: gold;")
        self.pass_username.setObjectName("pass_username")
        self.verticalLayout_17.addWidget(self.pass_username)
        self.verticalLayout_4.addWidget(self.groupBox_17)
        self.line1_6 = QtWidgets.QFrame(self.groupBox_13)
        self.line1_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_6.setObjectName("line1_6")
        self.verticalLayout_4.addWidget(self.line1_6)
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.register_b = QtWidgets.QPushButton(self.groupBox_18)
        self.register_b.setMinimumSize(QtCore.QSize(215, 31))
        self.register_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;}\n"
                                      "\n"
                                      "#register_b:pressed {\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.register_b.setObjectName("register_b")
        self.verticalLayout_20.addWidget(self.register_b)
        self.verticalLayout_4.addWidget(self.groupBox_18)
        self.verticalLayout_8.addWidget(self.groupBox_13)
        self.log_tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.loginUsername = QtWidgets.QLineEdit(self.groupBox_19)
        self.loginUsername.setMinimumSize(QtCore.QSize(215, 31))
        self.loginUsername.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.loginUsername.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                         "border-radius:5px;\n"
                                         "color: gold;")
        self.loginUsername.setObjectName("loginUsername")
        self.verticalLayout_11.addWidget(self.loginUsername)
        self.loginPass = QtWidgets.QLineEdit(self.groupBox_19)
        self.loginPass.setMinimumSize(QtCore.QSize(215, 31))
        self.loginPass.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.loginPass.setAutoFillBackground(False)
        self.loginPass.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                     "border-radius:5px;\n"
                                     "color: gold;")
        self.loginPass.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.loginPass.setObjectName("loginPass")
        self.verticalLayout_11.addWidget(self.loginPass)
        self.verticalLayout_7.addWidget(self.groupBox_19)
        self.line1_9 = QtWidgets.QFrame(self.groupBox_14)
        self.line1_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_9.setObjectName("line1_9")
        self.verticalLayout_7.addWidget(self.line1_9)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_20.setTitle("")
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.renter_b = QtWidgets.QPushButton(self.groupBox_20)
        self.renter_b.setMinimumSize(QtCore.QSize(215, 31))
        self.renter_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                    "border-radius:5px;\n"
                                    "color: gold;}\n"
                                    "\n"
                                    "#renter_b:pressed {\n"
                                    "    background: gold;\n"
                                    "    color:  rgb(41, 43, 53);\n"
                                    "}    ")
        self.renter_b.setObjectName("renter_b")
        self.verticalLayout_13.addWidget(self.renter_b)
        self.verticalLayout_7.addWidget(self.groupBox_20)
        self.verticalLayout_15.addWidget(self.groupBox_14)
        self.log_tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_16.addWidget(self.log_tabWidget)
        self.stackedWidget.addWidget(self.log_form)
        self.def_travel = QtWidgets.QWidget()
        self.def_travel.setObjectName("def_travel")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.def_travel)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.groupBox_15 = QtWidgets.QGroupBox(self.def_travel)
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.create_dey = QtWidgets.QComboBox(self.groupBox)
        self.create_dey.setMinimumSize(QtCore.QSize(121, 31))
        self.create_dey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_dey.setStyleSheet("*{\n"
                                      "background: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;\n"
                                      "}\n"
                                      "\n"
                                      "#create_dey:pressed {\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.create_dey.setObjectName("create_dey")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.create_dey.addItem("")
        self.horizontalLayout_3.addWidget(self.create_dey)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet("border: none;")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.create_month = QtWidgets.QComboBox(self.groupBox)
        self.create_month.setMinimumSize(QtCore.QSize(121, 31))
        self.create_month.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_month.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                        "border-radius:5px;\n"
                                        "color: gold;\n"
                                        "}\n"
                                        "#create_month:pressed{\n"
                                        "    background-color: gold;\n"
                                        "    color:  black;\n"
                                        "}    ")
        self.create_month.setObjectName("create_month")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.create_month.addItem("")
        self.horizontalLayout_3.addWidget(self.create_month)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("border: none;")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_15)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_6)
        self.timeEdit.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                    "border-radius:5px;\n"
                                    "color: gold;")
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_5.addWidget(self.timeEdit)
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setStyleSheet("border: none;")
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.verticalLayout.addWidget(self.frame_6)
        self.line1_7 = QtWidgets.QFrame(self.groupBox_15)
        self.line1_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_7.setObjectName("line1_7")
        self.verticalLayout.addWidget(self.line1_7)
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_21)
        self.label.setMinimumSize(QtCore.QSize(215, 31))
        self.label.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                 "border-radius:5px;\n"
                                 "color: rgba(255,215,0,0.3);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.create_dest = QtWidgets.QLineEdit(self.groupBox_21)
        self.create_dest.setMinimumSize(QtCore.QSize(215, 31))
        self.create_dest.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                       "border-radius:5px;\n"
                                       "color: gold;")
        self.create_dest.setObjectName("create_dest")
        self.verticalLayout_2.addWidget(self.create_dest)
        self.frame = QtWidgets.QFrame(self.groupBox_21)
        self.frame.setStyleSheet("border :0px ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setMinimumSize(QtCore.QSize(80, 31))
        self.spinBox.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                   "border-radius:5px;\n"
                                   "color: gold;")
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.groupBox_21)
        self.frame_7 = QtWidgets.QFrame(self.groupBox_15)
        self.frame_7.setStyleSheet("border :1px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit.setStyleSheet("background-color: rgb(41, 43, 53);\n"
                                    "border-radius:5px;\n"
                                    "color: gold;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setStyleSheet("border: none;")
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.verticalLayout.addWidget(self.frame_7)
        self.line1_8 = QtWidgets.QFrame(self.groupBox_15)
        self.line1_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_8.setObjectName("line1_8")
        self.verticalLayout.addWidget(self.line1_8)
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.groupBox_22)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.submit_b = QtWidgets.QPushButton(self.groupBox_22)
        self.submit_b.setMinimumSize(QtCore.QSize(215, 31))
        self.submit_b.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.submit_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                    "border-radius:5px;\n"
                                    "color: gold;}\n"
                                    "\n"
                                    "#submit_b:pressed {\n"
                                    "    background: gold;\n"
                                    "    color:  rgb(41, 43, 53);\n"
                                    "}    ")
        self.submit_b.setObjectName("submit_b")
        self.verticalLayout_21.addWidget(self.submit_b)
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.myTravel = QtWidgets.QPushButton(self.groupBox_23)
        self.myTravel.setMinimumSize(QtCore.QSize(215, 31))
        self.myTravel.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.myTravel.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                    "border-radius:5px;\n"
                                    "color: gold;}\n"
                                    "\n"
                                    "#myTravel:pressed {\n"
                                    "    background: gold;\n"
                                    "    color:  rgb(41, 43, 53);\n"
                                    "}    ")
        self.myTravel.setObjectName("myTravel")
        self.verticalLayout_14.addWidget(self.myTravel)
        self.singup_b_5 = QtWidgets.QPushButton(self.groupBox_23)
        self.singup_b_5.setMinimumSize(QtCore.QSize(215, 31))
        self.singup_b_5.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.singup_b_5.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;}\n"
                                      "\n"
                                      "#singup_b_5:pressed {\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.singup_b_5.setObjectName("singup_b_5")
        self.verticalLayout_14.addWidget(self.singup_b_5)
        self.delAcount_b = QtWidgets.QPushButton(self.groupBox_23)
        self.delAcount_b.setMinimumSize(QtCore.QSize(215, 31))
        self.delAcount_b.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                       "border-radius:5px;\n"
                                       "color: gold;}\n"
                                       "\n"
                                       "#delAcount_b:pressed {\n"
                                       "    background: gold;\n"
                                       "    color:  rgb(41, 43, 53);\n"
                                       "}    ")
        self.delAcount_b.setObjectName("delAcount_b")
        self.verticalLayout_14.addWidget(self.delAcount_b)
        self.verticalLayout_21.addWidget(self.groupBox_23)
        self.verticalLayout.addWidget(self.groupBox_22)
        self.verticalLayout_19.addWidget(self.groupBox_15)
        self.stackedWidget.addWidget(self.def_travel)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setMinimumSize(QtCore.QSize(351, 18))
        self.label_5.setMaximumSize(QtCore.QSize(351, 18))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.listWidget = QtWidgets.QListWidget(self.page_3)
        self.listWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.listWidget.setStyleSheet("*{\n"
                                      "background: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;\n"
                                      "}\n"
                                      "\n"
                                      "#listWidget:pressed {\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_12.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setMinimumSize(QtCore.QSize(350, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(350, 30))
        self.pushButton.setStyleSheet("*{background-color: rgb(41, 43, 53);\n"
                                      "border-radius:5px;\n"
                                      "color: gold;}\n"
                                      "\n"
                                      "#pushButton:pressed {\n"
                                      "    background: gold;\n"
                                      "    color:  rgb(41, 43, 53);\n"
                                      "}    ")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.pushButton)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.main_tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.main_tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.main_tabWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(3)
        self.stackedWidget.setCurrentIndex(0)
        self.log_tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        #########
        self.singup_b_5.clicked.connect(
            lambda _: self.stackedWidget.setCurrentIndex(0))
        self.main_tabWidget.setCurrentIndex(0)
        self.log_tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)

########

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", ":تاریخ"))
        self.search_day.setItemText(0, _translate("Form", "01"))
        self.search_day.setItemText(1, _translate("Form", "02"))
        self.search_day.setItemText(2, _translate("Form", "03"))
        self.search_day.setItemText(3, _translate("Form", "04"))
        self.search_day.setItemText(4, _translate("Form", "05"))
        self.search_day.setItemText(5, _translate("Form", "06"))
        self.search_day.setItemText(6, _translate("Form", "07"))
        self.search_day.setItemText(7, _translate("Form", "08"))
        self.search_day.setItemText(8, _translate("Form", "09"))
        self.search_day.setItemText(9, _translate("Form", "10"))
        self.search_day.setItemText(10, _translate("Form", "11"))
        self.search_day.setItemText(11, _translate("Form", "12"))
        self.search_day.setItemText(12, _translate("Form", "13"))
        self.search_day.setItemText(13, _translate("Form", "14"))
        self.search_day.setItemText(14, _translate("Form", "15"))
        self.search_day.setItemText(15, _translate("Form", "16"))
        self.search_day.setItemText(16, _translate("Form", "17"))
        self.search_day.setItemText(17, _translate("Form", "18"))
        self.search_day.setItemText(18, _translate("Form", "19"))
        self.search_day.setItemText(19, _translate("Form", "20"))
        self.search_day.setItemText(20, _translate("Form", "21"))
        self.search_day.setItemText(21, _translate("Form", "22"))
        self.search_day.setItemText(22, _translate("Form", "23"))
        self.search_day.setItemText(23, _translate("Form", "24"))
        self.search_day.setItemText(24, _translate("Form", "25"))
        self.search_day.setItemText(25, _translate("Form", "26"))
        self.search_day.setItemText(26, _translate("Form", "27"))
        self.search_day.setItemText(27, _translate("Form", "28"))
        self.search_day.setItemText(28, _translate("Form", "29"))
        self.search_day.setItemText(29, _translate("Form", "30"))
        self.search_day.setItemText(30, _translate("Form", "31"))
        self.label_9.setText(_translate("Form", "روز:"))
        self.search_month.setItemText(0, _translate("Form", "01"))
        self.search_month.setItemText(1, _translate("Form", "02"))
        self.search_month.setItemText(2, _translate("Form", "03"))
        self.search_month.setItemText(3, _translate("Form", "04"))
        self.search_month.setItemText(4, _translate("Form", "05"))
        self.search_month.setItemText(5, _translate("Form", "06"))
        self.search_month.setItemText(6, _translate("Form", "07"))
        self.search_month.setItemText(7, _translate("Form", "08"))
        self.search_month.setItemText(8, _translate("Form", "09"))
        self.search_month.setItemText(9, _translate("Form", "10"))
        self.search_month.setItemText(10, _translate("Form", "11"))
        self.search_month.setItemText(11, _translate("Form", "12"))
        self.label_6.setText(_translate("Form", "ماه:"))
        self.search_origin.setText(_translate("Form", "مبدا"))
        self.search_dest.setText(_translate("Form", "مقصد"))
        self.search_travel_b.setText(_translate("Form", "جستوجو"))
        self.search_travel_b.setShortcut(_translate("Form", "Return"))
        self.myticket_b.setText(_translate("Form", "بلیط های من"))
        self.myticket_b.setShortcut(_translate("Form", "Right"))
        self.label_10.setText(_translate(
            "Form", "                برای انتخاب روی هر  سفر  دوبار کلیک کنید"))
        self.return_b1.setText(_translate("Form", "بازگشت"))
        self.return_b1.setShortcut(_translate("Form", "Left"))
        self.groupBox_3.setTitle(_translate("Form", "ثبت بلیط"))
        self.name_input.setText(_translate("Form", "نام و نام خانوادگی"))
        self.meliCode_input.setText(_translate("Form", "کد ملی"))
        self.number_input.setText(_translate("Form", "شماره تماس"))
        self.label_2.setText(_translate("Form", "تعداد مسافر ها:"))
        self.confrim_input_b.setText(_translate("Form", "تایید"))
        self.confrim_input_b.setShortcut(_translate("Form", "Return"))
        self.return_b2.setText(_translate("Form", "بازگشت"))
        self.return_b2.setShortcut(_translate("Form", "Left"))
        self.code_input.setText(_translate("Form", "کد پیگیری یا کد ملی"))
        self.find_b.setText(_translate("Form", "جست و جو"))
        self.find_b.setShortcut(_translate("Form", "Return"))
        self.pushButton_7.setText(_translate("Form", "بازگشت"))
        self.pushButton_7.setShortcut(_translate("Form", "Return"))
        self.label_11.setText(_translate(
            "Form", "                برای حدف روی هر  سفر  دوبار کلیک کنید"))
        self.return_b4.setText(_translate("Form", "بازگشت"))
        self.return_b4.setShortcut(_translate("Form", "Left"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(
            self.tab), _translate("Form", "خرید بلیط"))
        self.singup_username.setText(_translate("Form", "شماره پایانه"))
        self.username_input_3.setText(_translate("Form", "شهر"))
        self.pass_username.setText(_translate("Form", "رمز"))
        self.register_b.setText(_translate("Form", "ثبت نام"))
        self.register_b.setShortcut(_translate("Form", "Return"))
        self.log_tabWidget.setTabText(self.log_tabWidget.indexOf(
            self.tab_4), _translate("Form", "ثبت نام"))
        self.loginUsername.setText(_translate("Form", "شماره پایانه"))
        self.loginPass.setText(_translate("Form", "رمز"))
        self.renter_b.setText(_translate("Form", "ورود"))
        self.renter_b.setShortcut(_translate("Form", "Return"))
        self.log_tabWidget.setTabText(self.log_tabWidget.indexOf(
            self.tab_5), _translate("Form", "ورود"))
        self.create_dey.setItemText(0, _translate("Form", "01"))
        self.create_dey.setItemText(1, _translate("Form", "02"))
        self.create_dey.setItemText(2, _translate("Form", "03"))
        self.create_dey.setItemText(3, _translate("Form", "04"))
        self.create_dey.setItemText(4, _translate("Form", "05"))
        self.create_dey.setItemText(5, _translate("Form", "06"))
        self.create_dey.setItemText(6, _translate("Form", "07"))
        self.create_dey.setItemText(7, _translate("Form", "08"))
        self.create_dey.setItemText(8, _translate("Form", "09"))
        self.create_dey.setItemText(9, _translate("Form", "10"))
        self.create_dey.setItemText(10, _translate("Form", "11"))
        self.create_dey.setItemText(11, _translate("Form", "12"))
        self.create_dey.setItemText(12, _translate("Form", "13"))
        self.create_dey.setItemText(13, _translate("Form", "14"))
        self.create_dey.setItemText(14, _translate("Form", "15"))
        self.create_dey.setItemText(15, _translate("Form", "16"))
        self.create_dey.setItemText(16, _translate("Form", "17"))
        self.create_dey.setItemText(17, _translate("Form", "18"))
        self.create_dey.setItemText(18, _translate("Form", "19"))
        self.create_dey.setItemText(19, _translate("Form", "20"))
        self.create_dey.setItemText(20, _translate("Form", "21"))
        self.create_dey.setItemText(21, _translate("Form", "22"))
        self.create_dey.setItemText(22, _translate("Form", "23"))
        self.create_dey.setItemText(23, _translate("Form", "24"))
        self.create_dey.setItemText(24, _translate("Form", "25"))
        self.create_dey.setItemText(25, _translate("Form", "26"))
        self.create_dey.setItemText(26, _translate("Form", "27"))
        self.create_dey.setItemText(27, _translate("Form", "28"))
        self.create_dey.setItemText(28, _translate("Form", "29"))
        self.create_dey.setItemText(29, _translate("Form", "30"))
        self.create_dey.setItemText(30, _translate("Form", "31"))
        self.label_8.setText(_translate("Form", "روز:"))
        self.create_month.setItemText(0, _translate("Form", "01"))
        self.create_month.setItemText(1, _translate("Form", "02"))
        self.create_month.setItemText(2, _translate("Form", "03"))
        self.create_month.setItemText(3, _translate("Form", "04"))
        self.create_month.setItemText(4, _translate("Form", "05"))
        self.create_month.setItemText(5, _translate("Form", "06"))
        self.create_month.setItemText(6, _translate("Form", "07"))
        self.create_month.setItemText(7, _translate("Form", "08"))
        self.create_month.setItemText(8, _translate("Form", "09"))
        self.create_month.setItemText(9, _translate("Form", "10"))
        self.create_month.setItemText(10, _translate("Form", "11"))
        self.create_month.setItemText(11, _translate("Form", "12"))
        self.label_4.setText(_translate("Form", "ماه:"))
        self.label_13.setText(_translate("Form", "ساعت حرکت:"))
        self.label.setText(_translate("Form", "مبدا: "))
        self.create_dest.setText(_translate("Form", "مقصد"))
        self.label_3.setText(_translate("Form", "ظرفیت :"))
        self.lineEdit.setText(_translate("Form", "تومان"))
        self.label_14.setText(_translate("Form", "قیمت برای هر نفر:"))
        self.submit_b.setText(_translate("Form", "ثبت سفر"))
        self.submit_b.setShortcut(_translate("Form", "Return"))
        self.myTravel.setText(_translate("Form", "سفر های من"))
        self.singup_b_5.setText(_translate("Form", "خروج از حساب کاربری"))
        self.singup_b_5.setShortcut(_translate("Form", "Left"))
        self.delAcount_b.setText(_translate("Form", "حذف حساب کاربری "))
        self.label_5.setText(_translate(
            "Form", "                برای انتخاب روی هر  سفر  دوبار کلیک کنید"))
        self.pushButton.setText(_translate("Form", "بازگشت"))
        self.pushButton.setShortcut(_translate("Form", "Left"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(
            self.tab_2), _translate("Form", "سفر جدید"))

    # ----------------------

        self.register_b.clicked.connect(self.createAdmin)
        self.renter_b.clicked.connect(self.login)
        self.singup_b_5.clicked.connect(self.logout)
        self.submit_b.clicked.connect(self.submit_tra)
        self.delAcount_b.clicked.connect(self.del_acount)
        self.myTravel.clicked.connect(self.getTravel)
        self.pushButton.clicked.connect(self.return1)
        self.return_b1.clicked.connect(self.return2)
        self.search_travel_b.clicked.connect(self.searchTravel)
        self.listWidget_2.doubleClicked.connect(self.chooseToTravel)
        self.confrim_input_b.clicked.connect(self.registerToTravel)
        self.return_b2.clicked.connect(
            lambda: self.stackedWidget_2.setCurrentIndex(1))
        self.myticket_b.clicked.connect(self.showTicket)
        self.find_b.clicked.connect(self.findTravel)
        self.pushButton_7.clicked.connect(
            lambda: self.stackedWidget_2.setCurrentIndex(0))
        self.return_b4.clicked.connect(self.return3)
        self.listWidget.doubleClicked.connect(self.delTravel)
        self.listWidget_3.doubleClicked.connect(self.delTicket)


# --------------------
# --------------------


    def return1(self):

        self.stackedWidget.setCurrentIndex(1)
        self.listWidget.clear()
        self.create_dey.setCurrentIndex(0)
        self.create_month.setCurrentIndex(0)
        self.singup_username.setText("مقصد")
        self.spinBox.setValue(1)
        self.notifLable.setText("")

    def return2(self):

        self.stackedWidget_2.setCurrentIndex(0)
        self.listWidget_2.clear()
        self.search_day.setCurrentIndex(0)
        self.search_month.setCurrentIndex(0)
        self.search_origin.setText("مبدا")
        self.search_dest.setText("مقصد")
        self.notifLable.setText("")

    def return3(self):

        self.stackedWidget_2.setCurrentIndex(3)
        self.code_input.setText("کد پیگیری یا کد ملی")
        self.search_day.setCurrentIndex(0)
        self.search_month.setCurrentIndex(0)
        self.search_origin.setText("مبدا")
        self.search_dest.setText("مقصد")
        self.listWidget_3.clear()
        self.notifLable.setText("")

    def createAdmin(self):

        admin = [self.singup_username.text(), self.username_input_3.text(),
                 self.pass_username.text()]

        if admin[0] == "شماره پایانه" or admin[1] == "شهر" or admin[2] == "رمز":
            self.notifLable.setText("لطفا اطلاعات خواسته شده را وارد نمایید")
            self.singup_username.setText("شماره پایانه")
            self.username_input_3.setText("شهر")
            self.pass_username.setText("رمز")
        else:

            try:

                with open("admin.txt", "rb")as f:
                    output = pickle.load(f)

                if admin[0] not in output:
                    output[admin[0]] = [admin[1], admin[2]]

                    self.notifLable.setText("ثبت نام با موفیقیت انجام شد")
                    with open("admin.txt", "wb")as f:
                        pickle.dump(output, f)

                else:

                    self.notifLable.setText(
                        "کاربری با چنین اطلاعاتی از قبل وجود داشته")

                    # time.sleep(2)
                    # self.notifLable.setText(" ")

            except:

                with open("admin.txt", "wb")as f:

                    output = dict()
                    output[admin[0]] = [admin[1], admin[2]]
                    pickle.dump(output, f)

                self.notifLable.setText("ثبت نام با موفیقیت انجام شد")

            self.singup_username.setText("شماره پایانه")
            self.username_input_3.setText("شهر")
            self.pass_username.setText("رمز")

    def login(self):

        global userID

        try:
            global admin

            admin = [self.loginUsername.text(), self.loginPass.text()]

            f = open("admin.txt", "rb")
            output = pickle.load(f)

            if admin[0] in output and output[admin[0]][1] == admin[1]:

                self.notifLable.setText(
                    f"ورود کاربر {admin[0]} با موفقیت همراه بود")
                self.stackedWidget.setCurrentWidget(self.def_travel)
                self.create_dey.setCurrentIndex(0)
                self.create_month.setCurrentIndex(0)
                self.create_dest.setText('مقصد')
                self.spinBox.setValue(0)
                self.label.setText(f"مبدا: {output[admin[0]][0]}")
                f.close()
                userID = admin[0]

            else:
                self.notifLable.setText("چنین کاربری پیدا نشد")

            self.loginUsername.setText("شناسه کاربری")
            self.loginPass.setText("رمز")

        except :

            with open("admin.txt", "wb") as f:
                dic1 = dict()
                pickle.dump(dic1, f)

            f = open("admin.txt", "rb")
            output = pickle.load(f)

            if admin[0] in output and output[admin[0]][1] == admin[1]:

                self.notifLable.setText(
                    f"ورود کاربر {admin[0]} با موفقیت همراه بود")
                self.stackedWidget.setCurrentWidget(self.def_travel)
                self.create_dey.setCurrentIndex(0)
                self.create_month.setCurrentIndex(0)
                self.create_dest.setText('مقصد')
                self.spinBox.setValue(0)
                self.label.setText(f"مبدا: {output[admin[0]][0]}")
                f.close()

                userID = admin[0]

            else:

                self.notifLable.setText("چنین کاربری پیدا نشد")

            self.loginUsername.setText("شناسه کاربری")
            self.loginPass.setText("رمز")
            self.notifLable.setText("لطفا اطلاعات خواسته شده را وارد نمایید")

    def logout(self):
        self.stackedWidget.setCurrentIndex(0)
        self.notifLable.setText(f"خروج کاربر {admin[0]} با موفقیت همراه بود")

    def submit_tra(self):
        flag = True
        data = [self.create_dey.currentText(), self.create_month.currentText(), self.create_dest.text(), self.spinBox.text(), self.label.text(), userID, [], self.spinBox.text(
        ), [self.create_dey.currentText(), self.create_month.currentText(), self.create_dest.text(), self.label.text()[6:]], self.timeEdit.time(), self.lineEdit.text()]

        if data[2] == "مقصد" or data[3] == "0":
            self.notifLable.setText("لطفا اطلاعات خواسته شده را وارد نمایید")
            flag = False

        elif int(data[1]) < int(JalaliDate.today().isoformat()[5:7]):
            self.notifLable.setText("سفر در زمان هنوز امکان پذیر نمی باشد")
            flag = False

        elif data[1] == JalaliDate.today().isoformat()[5:7] and int(data[0]) < int(JalaliDate.today().isoformat()[8:10]):
            self.notifLable.setText("سفر در زمان هنوز امکان پذیر نمی باشد")
            flag = False

        if data[10] == "تومان":
            self.notifLable.setText("لطفا اطلاعات خواسته شده را وارد نمایید")
            flag = False

        if flag:

            try:

                with open("travelDic.txt", "rb")as f:
                    output = pickle.load(f)

                output[JalaliDateTime.now().isoformat()[11:19]] = data

                with open("travelDic.txt", "wb")as f:
                    pickle.dump(output, f)

                self.notifLable.setText("ثبت سفر با موفیقیت انجام شد")

            except:

                with open("travelDic.txt", "wb")as f:
                    output = dict()
                    output[JalaliDateTime.now().isoformat()[11:19]] = data
                    pickle.dump(output, f)

                self.notifLable.setText("ثبت سفر با موفیقیت انجام شد")

    def del_acount(self):

        with open("admin.txt", "rb")as f:
            output = pickle.load(f)

        output.pop(admin[0])

        with open("admin.txt", "wb")as f:
            pickle.dump(output, f)

        with open("travelDic.txt", "rb")as f:
            output = pickle.load(f)

        for id, val in output.items():

            if admin[0] in val:
                output.pop(id)
        with open("travelDic.txt", "wb")as f:
            pickle.dump(output, f)

        self.notifLable.setText(f"حساب کاربری {admin[0]} با موفقیت حذف شد")
        self.stackedWidget.setCurrentIndex(0)

    def getTravel(self):
        try:
            with open("travelDic.txt", "rb")as f2:
                output = pickle.load(f2)
            travelStrList = []
            for id, value in output.items():
                if admin[0] == value[5]:
                    str = f"id: {id} - date: {value[1]}\\{value[0]} - time: {value[9]} - origin: {value[4][6:]} - destination: {value[2]} - capacity: {value[3]} - current capacity:{value[7]} - price: {value[10]} - {value[6]}"
                    travelStrList.append(str)
            self.listWidget.addItems(travelStrList)
            self.stackedWidget.setCurrentIndex(2)
        except Exception as ex:
            print(ex)
            self.notifLable.setText(" سفری تعریف نشده است")

    def searchTravel(self):
        self.listWidget_2.clear()
        flag = True

        data1 = [self.search_day.currentText(), self.search_month.currentText(
        ), self.search_dest.text(), self.search_origin.text()]

        if data1[2] == "مقصد" or data1[3] == "0":
            self.notifLable.setText("لطفا اطلاعات خواسته شده را وارد نمایید")
            flag = False

        elif int(data1[1]) < int(JalaliDate.today().isoformat()[5:7]):
            self.notifLable.setText("سفر در زمان هنوز امکان پذیر نمی باشد")
            flag = False

        elif data1[1] == JalaliDate.today().isoformat()[5:7] and int(data1[0]) < int(JalaliDate.today().isoformat()[8:10]):
            self.notifLable.setText("سفر در زمان هنوز امکان پذیر نمی باشد")
            flag = False

        if flag:

            with open("travelDic.txt", "rb")as f:
                output = pickle.load(f)

            resTravel = []

            for id, item in output.items():
                if data1 in item:
                    travelStr = f"{id} - date: - {item[1]}\\{item[0]} - time: {item[-2]} - origin: {item[4][6:]} - destination: {item[2]} - current capacity:{item[7]} - price: {item[10]}"
                    resTravel.append(travelStr)

            self.stackedWidget_2.setCurrentIndex(1)
            self.listWidget_2.addItems(resTravel)
            self.notifLable.setText(
                f" در جست و جو تعداد {len(resTravel)} سفر پیدا شد")

    def chooseToTravel(self):
        self.stackedWidget_2.setCurrentIndex(2)

    def createCode(self):
        import random as r
        chars = "1234567890QWERTYUIOASDFGHJKLZXCVBNM"
        str = ''
        for _ in range(4):
            str += r.choice(chars)

        return str

    def registerToTravel(self):
        key = self.listWidget_2.currentItem().text()[0:8]
        flag = True
        code = self.createCode()

        userdata = [self.name_input.text(), self.meliCode_input.text(
        ), self.number_input.text(), code, self.passangerNumber_input.text()]

        with open("travelDic.txt", "rb")as f:
            output1 = pickle.load(f)

        if int(output1[key][7]) <= int(userdata[-1]):
            self.notifLable.setText("ظرفیت اتوبوس کمتر از تعداد مسافرین شما است")
            flag = False
        if 30 <= int(userdata[-1]):
            self.notifLable.setText("تعداد مسافرین بیش از حد مجاز")
            flag = False

        if userdata[1] == "نام و نام خانوادگی " or userdata[2] == "کد ملی" or userdata[2] == "شماره تماس" :
            self.notifLable.setText("لطفا اطلاعات خواسته شده را وارد نمایید")
            flag = False

        if flag:

            with open("travelDic.txt", "rb")as f:
                output = pickle.load(f)

            list1 = output[key][6]
            list1.append(userdata)

            val = output[key]
            x = val[7]
            z = int(x)
            z -= int(userdata[-1])
            output[key][7] = z

            with open("travelDic.txt", "wb")as f1:
                pickle.dump(output, f1)

            self.stackedWidget_2.setCurrentIndex(0)

            with open("travelDic.txt", "rb")as f:
                output1 = pickle.load(f)

            price = int(self.passangerNumber_input.value())*int(output1[key][10])

            self.notifLable.setText(
                f"خرید شما با پرداخت مبلغ {price} ثبت گردید   کد پیگیری: {code}")

    def showTicket(self):
        self.stackedWidget_2.setCurrentIndex(3)

    def findTravel(self):

        self.stackedWidget_2.setCurrentIndex(4)
        ticketlist = dict()

        with open("travelDic.txt", "rb")as f:
            output1 = pickle.load(f)

        code = self.code_input.text()

        for id, eachtravel in output1.items():
            for passanger in eachtravel[6]:
                if code in passanger:
                    ticketlist[id] = eachtravel
        resTravel = []

        for id, item in ticketlist.items():
            travelStr = f"{id}-date: {item[1]}\\{item[0]} time: {item[-2]} origin: {item[4][6:]}  destination: {item[2]}  current capacity:{item[7]} price: {item[10]} "
            resTravel.append(travelStr)

        self.listWidget_3.addItems(resTravel)

    def delTravel(self):
        key = self.listWidget.currentItem().text()[4:12]

        with open("travelDic.txt", "rb")as f:
            output1 = pickle.load(f)
        output1.pop(key)

        with open("travelDic.txt", "wb")as f:
            pickle.dump(output1, f)

        self.listWidget.clear()
        self.getTravel()
        self.notifLable.setText("سفر مورد نظر با موفقیت حذف شد")

    def delTicket(self):

        code = self.code_input.text()

        with open("travelDic.txt", "rb")as f:
            output1 = pickle.load(f)

        for id, val in output1.items():
            for passenger in val[6]:
                if code in passenger:
                    output1[id][6].remove(passenger)
                    x=output1[id][7]
                    output1[id][7]=int(x)+int(passenger[-1])


        with open("travelDic.txt", "wb")as f:
            pickle.dump(output1, f)

        with open("travelDic.txt", "rb")as f:
            output2 = pickle.load(f)
        self.listWidget_3.clear()

        resTravel = []

        for id, item in output2.items():
            for passen in item[6]:
                if code in passen:
                    travelStr = f"{id}-date: {item[1]}\\{item[0]} time: {item[-2]} origin: {item[4][6:]}  destination: {item[2]}  current capacity:{item[7]} price: {item[10]} "
                    resTravel.append(travelStr)

        self.listWidget_3.addItems(resTravel)


# --------------------------


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
